name: 'AgentShadow '
favicon: null
layout_spectrum: 0.73402
typography_spectrum: 0.48599
title: Universal Heroes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#9d9d9d'
    - '#797979'
    - '#373737'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
