name: 'AgentShadow '
favicon: null
layout_spectrum: 0.06624066410586238
typography_spectrum: 0.5110270101577044
title: Universal Heroes
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#bebebe'
    - '#3f3f41'
    - '#3ec0f9'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
