typography_spectrum: 0.2593985
color:
  saturation: 0.3125
  brandStrength: 0
  rhythmicContrast: 0
  brandColors:
    - '#010103'
    - '#2a2a32'
    - '#92635d'
    - '#b69879'
    - '#e3efed'
  lightness: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6632653
analytics:
  twitter: null
  google: null
  facebook: null
name: 'AgentShadow '
cta:
  bucket: null
  version: null
  domain: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: MISTER M STUDIO
description: Superpowers Activated
purpose: []
