typography_spectrum: 0.34934467962011695
color:
  saturation: 0.34869738621637225
  brandStrength: 0.568434800254181
  rhythmicContrast: 0.1470889502670616
  brandColors:
    - '#007DE7'
    - '#C1E7F0'
    - '#040D16'
    - '#51B4EF'
    - '#F2B077'
  lightness: 0.7161056990735233
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.23074370832182467
analytics:
  twitter: null
  google: null
  facebook: null
name: 'AgentShadow '
cta:
  bucket: null
  version: null
  domain: null
navigation:
  - name: I AM ANDREW
    url: 'http://www.andrewmorrissey.com/'
    type: external
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: MISTER M STUDIO
description: Superpowers Activated
purpose: []
